Repository nhn-on7/marketgg-gateway, pull requests merged in 2022-08, with the labels that each got.

#13 Gateway Error Handling
  src/main/java/com/nhnacademy/marketgg/gateway/handler/ErrorEntity.java
  src/main/java/com/nhnacademy/marketgg/gateway/handler/WebExceptionHandler.java
Labels: Feat

#15 정적 분석 결과 개선을 위한 코드 포매팅 및 문서화
  README.md
  src/main/java/com/nhnacademy/marketgg/gateway/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/gateway/entity/ErrorEntity.java
  src/main/java/com/nhnacademy/marketgg/gateway/exception/ClientHttpConnectionException.java
  src/main/java/com/nhnacademy/marketgg/gateway/exception/SecureManagerException.java
  src/main/java/com/nhnacademy/marketgg/gateway/filter/JwtAuthorizationFilter.java
  src/main/java/com/nhnacademy/marketgg/gateway/handler/WebExceptionHandler.java
  src/main/java/com/nhnacademy/marketgg/gateway/jwt/JwtUtils.java
  src/main/java/com/nhnacademy/marketgg/gateway/util/SecureUtils.java
Labels: Docs, Refactor

#17 X-Forwarded-For 헤더 로깅을 위한 Global Filter 적용
  src/main/java/com/nhnacademy/marketgg/gateway/filter/HeaderFilter.java
  src/main/resources/application.yml
Labels: Feat

#18 Chore: 로그 수정
  src/main/java/com/nhnacademy/marketgg/gateway/filter/HeaderFilter.java
  src/main/java/com/nhnacademy/marketgg/gateway/jwt/JwtUtils.java
  src/main/resources/application.yml
Labels: Refactor

#19 Chore: 배포 수정
  .github/workflows/ci-cd.yml
  .github/workflows/main.yml
Labels: Chore
